
comment: "This issue is closed because it does not meet our issue template. Please read it."

issueConfigs:
- content:
  - "Reduced Test Case"
  - "http"
  - "Bug Description"
- content:
  - "Reduced Test Case"
  - "not reproducible with a link"
  - "Bug Description"
- content:
  - "[x] I've already searched through"
  - "[x] Other people will find this feature useful"
- content:
  - "I love FullCalendar"

caseInsensitive: true
