
sudo: false # route build to the container-based infrastructure for a faster build

language: node_js
node_js: 13

cache:
  npm: false # don't do node_modules
  directories:
    - .yarn/cache
    - example-projects/next/node_modules
    - example-projects/nuxt/node_modules
    - example-projects/vue-vuex/node_modules
    - example-projects/vue-typescript/node_modules
    - example-projects/parcel/node_modules

env:
  global:
    - TZ="America/Los_Angeles" # for Headless Chrome. otherwise will be UTC, bad for tests
  jobs:
    - SCRIPT_NAME="ci:lint"
    - SCRIPT_NAME="ci:test"
    - SCRIPT_NAME="ci:test:react"
    - SCRIPT_NAME="ci:contrib-n-ex"

# by default, travis tries --frozen-lockfile flag, which is deprecated
install: yarn install

script: yarn run $SCRIPT_NAME
