yarnPath: .yarn/releases/yarn-2.4.2.cjs

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    # yarn wouldn't fetch correct version that was compatible with 2.x :(
    spec: "https://raw.githubusercontent.com/yarnpkg/berry/%40yarnpkg/plugin-workspace-tools/2.2.0/packages/plugin-workspace-tools/bin/%40yarnpkg/plugin-workspace-tools.js"

packageExtensions:
  "@nuxt/components@2.*":
    dependencies:
      consola: "*"
  "@vue/test-utils@2.*":
    dependencies:
      "@vue/compiler-dom": "*"

  # lazy libs that don't define jquery as a dependency
  components-jqueryui@*:
    dependencies:
      jquery: "*"
  jasmine-jquery@*:
    dependencies:
      jquery: "*"
  jquery-simulate@*:
    dependencies:
      jquery: "*"

  # problem (https://github.com/webpack/webpack-dev-server/issues/2807):
  # webpack-dev-middleware@3.x is not compatible with webpack 5
  #   but webpack-dev-middleware@4.x (already officially released) IS compatible.
  # when webpack-dev-server@4.x is out of beta and supports webpack-dev-middleware@4.x,
  #   update the example-projects/(react|vue)* packages (and others?)
  # when webpack-dev-server@4.x is out of beta and @angular-devkit/build-angula supports it,
  #   update packages-contrib/angular and example-projects/angular
  webpack-dev-server@~3.11.0:
    dependencies:
      webpack-dev-middleware: ^4.0.0
