yarnPath: ".yarn/releases/yarn-berry.cjs"

# https://github.com/vuejs/vue-cli/issues/5135#issuecomment-585163059
packageExtensions:
  "@vue/cli-service@*":
    peerDependencies:
      "@vue/cli-plugin-typescript": "*"
