yarnPath: ".yarn/releases/yarn-berry.cjs"

# pnpMode: "loose"

packageExtensions:

  # https://github.com/vuejs/vue-cli/issues/5135#issuecomment-585163059
  "@vue/cli-service@*":
    peerDependencies:
      "@vue/cli-plugin-typescript": "*"
      "@vue/cli-plugin-babel": "*"
      "@vue/cli-plugin-eslint": "*"

  # needed here: https://github.com/nuxt/nuxt.js/blob/v2.14.3/packages/cli/src/imports.js
  # but not listed here: https://github.com/nuxt/nuxt.js/blob/v2.14.3/packages/cli/package.json
  "@nuxt/cli@*":
    dependencies:
      "@nuxt/core": "*"
      "@nuxt/builder": "*"
      "@nuxt/webpack": "*"
      "@nuxt/generator": "*"
      "@nuxt/server": "*"
