
yarnPath: ".yarn/releases/yarn-2.3.3.cjs"

packageExtensions:

  # they need to update for webpack 5: https://github.com/webpack/webpack-dev-server/issues/2807
  "webpack-dev-server@~3.11.0":
    dependencies:
      "webpack-dev-middleware": "^4.0.0"
